### ISSUE TITLE
只见线程, 不见队列

### ISSUE THREAD

**Issue by codedever** [Roger3Lee/INC.Runtime.Queue#1]
抱歉兄弟, 我说了句大实话, 如果哪里说的不对, 还请赐教!
你的代码我大致看了下, 如题, 只见线程, 确实没看见队列; 所谓队列, 就是有先来后到的, 比如消息队列, 是指消息进来之后可以排着队一个个被处理的, 你的项目所有跟 Queue 有关的代码我都看了, 并没有发现有什么地方跟队列有关系. 或许你我对队列的理解不同, 所以, 我理解中您的项目是一个合体加强版的线程池/计划任务, 说的不对, 还请赐教!

**Comment by Roger3Lee** [comment]
确实是一个加强版的线程池，所说的队列只是Job队列提供给多线程处理而已。

**Comment by codedever** [comment]
OK, 懂了
你可以考虑引入 netmq 变成真正的队列

**Comment by Roger3Lee** [comment]
感谢你的建议。后续可能还会加入timeout的功能
