### ISSUE TITLE
请教下怎么获取job 的返回值?

### ISSUE THREAD

**Issue by redcatH** [Roger3Lee/INC.Runtime.Queue#2]
只能Job_OnResultChange是吗?

**Comment by redcatH** [comment]
Job_OnResultChange?

**Comment by Roger3Lee** [comment]
不好意思，长时间没有登陆github，Job类的中有一个继承了接口INotifyJobResultChange的类，这个就是为有返回值的job设计的， 只需要对OnResultChange事件进行hander就可以了
